### ISSUE TITLE
UART communication mode not working for current version

### ISSUE THREAD

**Issue by fireup924** [grblHAL/iMXRT1062#28]
Commenting out "#define USB_SERIAL_CDC 2" in my_machine.h to use UART on pins 0, 1 for Teensy4.1 does not work in current version. Seems like the board is just crashing and resetting itself.

**Comment by terjeio** [comment]
Oops, this was introduced when I added info to the `$pins` command for the serial port. Remove [these lines](https://github.com/grblHAL/iMXRT1062/blob/7773365f7e36b6ae0f1032d555a9a13967e737b9/grblHAL_Teensy4/src/uart.c#L469-L470) for now. I'll commit a fix later.

**Comment by fireup924** [comment]
Thanks, removing those lines fixed it.
