### ISSUE TITLE
Using the ethernet port

### ISSUE THREAD

**Issue by mundsen** [grblHAL/iMXRT1062#30]
Does software like LightBurn support using the Ethernet as an alternative to USB?

Or is the ethernet support for webui only?

**Comment by terjeio** [comment]
Any sender that can use "raw" telnet can use ethernet. I do not know if LigthBurn can, my own ioSender can use both Telnet and Websocket comms. puTTY can also connect via "raw" telnet, there is a checkbox for "Raw" mode.
