### ISSUE TITLE
LATHE Y to Z

### ISSUE THREAD

**Issue by harryeveraert** [grblHAL/iMXRT1062#56]
How can I change Y to Z for lathe.
config is ioSenderEdge2.041p8
board_T41U5XBB_SS and IMXRT1062 (update Jan 2023)
Thank you

**Comment by terjeio** [comment]
New [Edge version](http://www.io-engineering.com/downloads) with fix uploaded.

**Comment by harryeveraert** [comment]
Wonderful it works
Thank you
